spring:
 data:
   mongodb:
     username: ${MONGO_USER}
     password: ${MONGO_PASSWORD}
     database: ${MONGO_DATABASE}
     port: ${MONGO_PORT}
     host: ${MONGO_HOST}
 application:
  name: NewsService
server:
 port: 8081
 