spring:
  data:
   mongodb:
     database: keepnote
     port: 27017
     host: localhost
  application:
   name: UserProfileService
server:
 port: 8084
 
eureka:
  client:
    service-url:
      defalutZone : http://eurekaserver:password@localhost:8761/eureka/