FROM openjdk:11-jdk
WORKDIR usr/src
ADD ./target/newz-netflix-eureka-server-0.0.1-SNAPSHOT.jar usr/src/newz-netflix-eureka-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","newz-netflix-eureka-server-0.0.1-SNAPSHOT.jar"]